
driver: 
  name: vagrant
  customize:
    memory: 2048
    cpuexecutioncap: 70
platforms: 
  - 
    name: centos-7.1
    name: centos-6.8
provisioner: 
  name: chef_solo
  cookbook_files_glob: "**/*"
  require_chef_omnibus: 11.18.12
  solo_rb:
    verify_api_cert: true
    ssl_verify_mode: :verify_peer
    log_level: :info
suites: 
  - 
    attributes:
      workorder:
        rfcCi:
          ciAttributes:
            ansible_version: "2.2.2.0"
            pip_proxy_content: ""  
            playbook: "https://github.com/sleepyorion/ansible-playbook.git?path=java_playbook.yml"
    name: ansible
    run_list: 
      - recipe[ansible::add]